#
# Module manifest for module 'Shell-Contexts'
#
# Generated by: Jeremy Brinkley
#
# Generated on: 8/24/2020
#

@{
  RootModule = 'Shell-Contexts.psm1'
  ModuleVersion = '0.6.0'
  GUID = 'aa653768-02e2-4805-9a36-1ba494b210e1'
  Author = 'Jeremy Brinkley'
  CompanyName = 'Verizon Media'
  Copyright = '(c) 2020 Verizon Media. All rights reserved.'
  FileList = @(
    'Shell-Contexts.psd1',
    'Shell-Contexts.psm1',
    'Set-CurrentContext.ps1'
  )
  PrivateData = @{
    PSData = @{
      Tags = @('github')
    } 
  }
}

