#
# Module manifest for module 'Dotfile-Utilities'
#
# Generated by: Jeremy Brinkley
#
# Generated on: 10/7/2020
#

@{
  RootModule = 'Dotfile-Utilities.psm1'
  ModuleVersion = '0.5.0'
  GUID = 'ca455d6e-0f31-436d-b52e-a6a505603518'
  Author = 'Jeremy Brinkley'
  CompanyName = 'Verizon Media'
  Copyright = '(c) 2020 Verizon Media. All rights reserved.'
  FileList = @(
    'Dotfile-Utilities.psd1',
    'Dotfile-Utilities.psm1',
    'Send-Dotfiles.ps1'
  )
  PrivateData = @{
    PSData = @{
      Tags = @('github')
    } 
  }
}

