#!bash
rconf()
{
    local remote_file="$1"
    local local_file="$2"

    local server="$(echo $1 | cut -f1 -d:)"
    local rfile="$(echo $1 | cut -f2 -d:)"

    if [ -f "$local_file" -a ! -p "$local_file" ]
    then
        echo "$local_file exists, not removing" >&2
        return 1
    else
        rm -f "$local_file"
        mkfifo "$local_file"
        end=$(date +%s)
        # Half hour
        let end=end+1800
        while [ $(date +%s) -lt $end ]; do nc localhost 4404 >"$local_file"; done &
        ssh -f -L 4404:localhost:4404 -o "ExitOnForwardFailure yes" $server "while [ \$(date +%s) -lt $end ]; do nc -w 10 -l -p 4404 -c 'cat $rfile' 2>/dev/null; done"
    fi
}
